//
//  ResourceKeys.swift
//  WeatherToday
//
//  Created by alaattib on 27.07.2023.
//

import TextAttributes

enum ResourceKey {
    case resource(String)
    case generalInfoButton
    case generalCancelButton
    case generalOKButton
    case generalCompleteHeader
    case generalErrorHeader
    case generalWarningHeader
    case generalExitButton
    case generalNoInternet
    case mainpageWelcome
    case mainpageLogOffText
    case loginDomainHeader
    case loginDomainList
    case loginUsername
    case loginEmail
    case loginContinueButton
    case loginSMSOTPButton
    case loginSMSOTPHeader
    case loginSMSOTPText
    case loginSMSOTPResendText
    case loginSMSOTPResend
    case loginSMSOTPConfirmButton
    case loginLoginButton
    case loginPassword
    case loginSmsOtpAgainWarningMessage
    case phoneBookSearchPerson
    case phoneBookSearchMicrophoneListeningTitle
    case phoneBookSearchMicrophoneListeningSubtitle
    case phoneBookSearchMicrophoneListeningTitleInProgress
    case phoneBookSearchMicrophoneTitleError
    case phoneBookSearchMicrophoneSubtitleError
    case phoneBookSearchMicrophoneErrorHint
    case phoneBookSearchMicrophonePermissionTitle
    case phoneBookSearchMicrophonePermissionSubtitle
    case phoneBookSearchMicrophonePermissionFirstButton
    case phoneBookSearchMicrophonePermissionSecondButton
    case phoneBookSearchMicrophoneNoPermissionTitle
    case phoneBookSearchMicrophoneNoPermissionSubtitle
    case phoneBookSearchMicrophoneNoPermissionFirstButton
    case phoneBookSearchMicrophoneNoPermissionSecondButton
    case phoneBookSearchNoResults
    case myDeviceHeaderInfo
    case myDeviceUser
    case myDevicePassword
    case myDeviceExpireInfo(String)
    case myDeviceCreateNewPass
    case myDeviceCopied
    case agendaText
    case agendaNewVisitOption
    case agendaVisitListOption
    case agendaMenuHeader
    case agendaMenuText
    case agendaQuestionText
    case agendaSearchWithCustomerNo
    case agendaDetailedSearch
    case agendaCustomerNo
    case agendaSearchButton
    case agendaCustomerInformation
    case agendaCustomerInformationSeeAll
    case agendaVisitRequest
    case agendaVisitReqSubmitPopup
    case agendaVisitListStartDate
    case agendaVisitListEndDate
    case agendaBranch
    case agendaVisitList
    case agendaVisitListList
    case agendaCustomerName
    case agendaCustomerSecondName
    case agendaCustomerSurname
    case agendaShortname
    case agendaCitizenshipNumber
    case agendaTaxNo
    case agendaMenuTextSubmit
    case agendaVisitDate
    case agendaPersonelVisit
    case agendaPortfoyCode
    case agendaPYVisit
    case agendaVisitReason
    case agendaVisitResult
    case agendaVisitNote
    case agendaVisitSubmit
    case agendaResourceResult
    case agendaResourceResultCusNo(String)
    case agendaResourceResultTCKN(String)
    case agendaResourceResultVKN(String)
    case agendaResourceResultStatus(String)
    case agendaCreateContact
    case agendaCreateContactInfo
    case agendaCreateContactTCKN
    case agendaCreateContactPhoneNumber
    case agendaCreateContactBirthDate
    case agendaCreateContactCreate
    case agendaCreateContactResultInfo(String)
    case agendaVisitListOptionDateMsg
    case agendaVisitListOptionDateMsg1
    case agendaVisitDetail
    case agendaIsRevisitCustomer
    case agendaRevisitCustomerDate
    case agendaIsSoldSomethingToCustomer
    case agendaCreateCorporateInfo
    case agendaCreateCorporateVisitPer
    case agendaCreateCorporateFirmAuth
    case agendaCreateCorporateFirmAuthTitle
    case agendaCreateCorporateFirmSummaryActivity
    case agendaCreateCorporateFirmAction
    case agendaCreateCorporateGoods
    case agendaCreateCorporateBManagerComment
    case agendaCreateCorporateAggrecultureAddress
    case agendaCreateCorporateEmployeeCount
    case agendaCreateCorporateMountlySallary
    case agendaCreateCorporateSallaryBank
    case agendaCreateCorporateSallaryBankAggrement
    case agendaCreateCorporateAggrementEndDate
    case agendaCreateCorporateFirmSector
    case agendaCreateCorporateConsolideBankRisk
    case agendaCreateCorporateConsolideEndorsment
    case agendaCreateCorporateContinue
    case agendaVisitSubject
    case softOtpCreatePinHeader
    case softOtpCreatePinInfo
    case softOtpCreatePinWarning
    case softOtpCreatePinButton
    case softOtpSMSInfo
    case softOtpSMSPlaceHolder
    case softOtpSMSButton
    case softOtpHeader
    case softOtpChangeInfo
    case softOtpChangeButton
    case softOtpPinInfo
    case softOtpPinButton
    case softOtpChangePinHeader
    case softOtpChangePinInfo
    case softOtpChangePinWarning
    case softOtpChangePinButton
    case softOtpCompleteInfo(String)
    case softOtpSmsConfirmation
    case softOtpSmsVerificationInfo
    case softOtpPinPlaceHolder
    case softOtpPinPlaceHolderAgain
    case softOtpChangeCompleteInfo
    case softOtpCreatePinUserName
    case softOtpPinCopied
    case softOtpDifferentPin
    case softOtpWrongPin
    case softOtpWarningPinCount
    case softOtpWarningPinCountText
    case softOtpWarningPinEmpty
    case softOtpWarningSMSOTP
    case softOtpWarningWrongPin
    case softOtpCreatePinWarningAgainEmpty
    case biometricActivationTitle(String)
    case biometricLoginExp
    case biometricLoginActivationMessage(String)
    case biometricLoginActivateButton
    case biometricLoginPopUpMessage(String)
    case biometricLoginPopUpCancel(String)
    case biometricLoginContinue
    case biometricLoginCancelButton
    case biometricLoginCancelMessage(String)
    case biometricLoginNotEnrolled(String)
    case biometricLoginPermission(String)
    case biometricLoginSettingsButton
    case biometricLoginErrorMessage
    case biometricLoginID(String)
    case biometricLoginCancelInfo(String)
    case biometricLoginPopUpLogin(String)
    case rotaRota
    case rotaProcessNo
    case rotaProcessTask
    case rotaProcessApprove
    case rotaEmptyFlow
    case remoteWorkHeader
    case remoteWorkRemoteStartDate
    case remoteWorkRemoteFinishDate
    case remoteWorkTotalDayCount
    case remoteWorkTotalHoliday
    case remoteWorkNetDayCount
    case remoteWorkExplanation
    case remoteWorkButton
    case remoteWorkWarningAllText
    case remoteWorkInfoText
    case remoteWorkWarningDateStart
    case remoteWorkWarningDateEnd
    case beamerPackageNo
    case beamerUser
    case beamerPlanDate
    case beamercriteria
    case beamerplannedPublishDate
    case beamerrecordDate
    case beamerapplicationName
    case beamerenvRelationName
    case beamerpublishType
    case beameruserName
    case beamerunvalued
    case beameraccepted
    case beamerrejected
    case beamerpublishText
    case beamerdmlText
    case beamerdescription
    case beamerDetailHeader(String)
    case beamerDetailRejectedButton
    case beamerDetailAcceptedButton
    case beamerFilterClearButton
    case beamerFilterSearchButton
    case beamerFilterHeader
    case beamerFilterPackageNo
    case beamerFilterPlanedDate
    case beamerFilterApp
    case beamerFilterUser
    case beamerFilterEnvRelationName
    case beamerFilterUnvalued
    case delegationHeader
    case delegationExplanationText
    case delegationNewDelegation
    case delegationFollowUpCancel
    case delegationSearchUser
    case delegationFlow
    case delegationStatus
    case delegationDelegate
    case delegationDelegateText
    case delegationUser
    case delegationStartDate
    case delegationStartTime
    case delegationEndDate
    case delegationEndTime
    case delegationCompleted
    case delegationCompletedText
    case delegationFlowRole
    case delegationWarning
    case delegationWarningText
    case delegationUserNotFound
    case delegationContinue
    case transportationDate
    case transportationRoute
    case transportationSelectRoute
    case transportationSearchRoute
    case transportationText
    case transportationMorning
    case transportationEvening
    case transportationBoth
    case transportationSave
    case leaveHeaderTitle
    case leaveHeaderInfo
    case leaveMenuAnnualLeave
    case leaveExcuseLeave
    case leaveHealthReport
    case leaveMaternityLeave
    case leaveBreastFeeding
    case leaveFreeLeaving
    case leaveExcuseLeaveInfo
    case leaveExcuseLeaveAdministrativeLeave
    case leaveExcuseLeaveMarriedLeave
    case leaveExcuseLeavePaternityLeave
    case leaveExcuseLeaveMedicalDisaster
    case leaveExcuseLeaveRelocationLeave
    case leaveExcuseLeaveChildMarried
    case leaveExcuseLeaveDeathOfFirstDegreeRelative
    case leaveExcuseLeaveIlnessOfFirstDegreeRelative
    case leaveExcuseLeavePublicHoliday
    case leaveExcuseLeavePagePageInfo
    case leaveExcuseLeavePageTitle
    case leaveExcuseLeaveStartDate
    case leaveExcuseLeaveEndDate
    case leaveExcuseLeaveTotalDay
    case leaveExcuseLeaveUsageLeavingDay
    case leaveExcuseLeaveContactNumberInHoliday
    case leaveExcuseLeaveLastStepInfo
    case leaveExcuseLeaveConfirmationButtonInfo
    case leaveAnnualLeavePageTitle
    case leaveAnnualLeaveHeaderInfo
    case leaveGeneralOtherContactNumberInHoliday
    case leaveHealthReportHeader
    case leaveHealthReportDocumentInfoText
    case leaveGeneralExplanation
    case leaveFreeLeavingPageHeader
    case leaveFreeLeavingFreePostpartumLeave
    case leaveFreeLeavingOtherFreeLeave
    case leaveFreeLeavingPageInfoText
    case leaveFreeLeavingSecondPageText
    case leaveMaternityLeaveSinglePregnancy
    case leaveMaternityLeaveTwinPregnancyAndOthers
    case leaveBreastFeedingOneDayInWeek
    case leaveBreastFeedingOneAndHalfHoursInDay
    case leaveBreastFeedingPreferinInfoText
    case leaveBreastFeedingMonday
    case leaveBreastFeedingTuesday
    case leaveBreastFeedingWednesday
    case leaveBreastFeedingThursday
    case leaveBreastFeedingFriday
    case leaveBreastFeedingPreferingHoursText
    case leaveBreastFeedingFirstPreferingHours
    case leaveBreastFeedingSecondPreferingHours
    case leaveBreastFeedingThirdPreferingHours
    case leaveBreastFeedingFourthPreferingHours
    case leaveBreastFeedingFifthPreferingHours
    case leaveBreastFeedingSixthPreferingHours
    case leaveGeneralContinueButton
    case leaveGeneralCity
    case leaveGeneralTown
    case leaveGeneralStreet
    case leaveGeneralTelephoneNumber
    case leaveGeneralAdressVallidityDate
    case leaveGeneralAdressVallidityApproval
    case leaveGeneralSendButton

    var key: String {
        switch self {
        case let .resource(resourceKey):
            return resourceKey
        case .generalInfoButton:
            return "General.InfoButton"
        case .generalCancelButton:
            return "General.CancelButton"
        case .generalOKButton:
            return "General.OKButton"
        case .generalCompleteHeader:
            return "General.CompleteHeader"
        case .generalErrorHeader:
            return "General.ErrorHeader"
        case .generalWarningHeader:
            return "General.WarningHeader"
        case .generalExitButton:
            return "General.ExitButton"
        case .generalNoInternet:
            return "General.NoInternet"
        case .mainpageWelcome:
            return "Mainpage.Welcome"
        case .mainpageLogOffText:
            return "Mainpage.LogOffText"
        case .loginDomainHeader:
            return "Login.DomainHeader"
        case .loginDomainList:
            return "Login.DomainList"
        case .loginUsername:
            return "Login.Username"
        case .loginEmail:
            return "Login.Email"
        case .loginContinueButton:
            return "Login.ContinueButton"
        case .loginSMSOTPButton:
            return "Login.SMSOTPButton"
        case .loginSMSOTPHeader:
            return "Login.SMSOTP.Header"
        case .loginSMSOTPText:
            return "Login.SMSOTP.Text"
        case .loginSMSOTPResendText:
            return "Login.SMSOTP.ResendText"
        case .loginSMSOTPResend:
            return "Login.SMSOTP.Resend"
        case .loginSMSOTPConfirmButton:
            return "Login.SMSOTP.ConfirmButton"
        case .loginLoginButton:
            return "Login.LoginButton"
        case .loginPassword:
            return "Login.Password"
        case .loginSmsOtpAgainWarningMessage:
            return "Login.SmsOtpAgain.WarningMessage"
        case .phoneBookSearchPerson:
            return "Phone.Book.Search.Person"
        case .phoneBookSearchMicrophoneListeningTitle:
            return "Phone.Book.Search.Microphone.ListeningTitle"
        case .phoneBookSearchMicrophoneListeningSubtitle:
            return "Phone.Book.Search.Microphone.ListeningSubtitle"
        case .phoneBookSearchMicrophoneListeningTitleInProgress:
            return "Phone.Book.Search.Microphone.ListeningTitleInProgress"
        case .phoneBookSearchMicrophoneTitleError:
            return "Phone.Book.Search.Microphone.TitleError"
        case .phoneBookSearchMicrophoneSubtitleError:
            return "Phone.Book.Search.Microphone.SubtitleError"
        case .phoneBookSearchMicrophoneErrorHint:
            return "Phone.Book.Search.Microphone.ErrorHint"
        case .phoneBookSearchMicrophonePermissionTitle:
            return "Phone.Book.Search.Microphone.PermissionTitle"
        case .phoneBookSearchMicrophonePermissionSubtitle:
            return "Phone.Book.Search.Microphone.PermissionSubtitle"
        case .phoneBookSearchMicrophonePermissionFirstButton:
            return "Phone.Book.Search.Microphone.PermissionFirstButton"
        case .phoneBookSearchMicrophonePermissionSecondButton:
            return "Phone.Book.Search.Microphone.PermissionSecondButton"
        case .phoneBookSearchMicrophoneNoPermissionTitle:
            return "Phone.Book.Search.Microphone.NoPermissionTitle"
        case .phoneBookSearchMicrophoneNoPermissionSubtitle:
            return "Phone.Book.Search.Microphone.NoPermissionSubtitle"
        case .phoneBookSearchMicrophoneNoPermissionFirstButton:
            return "Phone.Book.Search.Microphone.NoPermissionFirstButton"
        case .phoneBookSearchMicrophoneNoPermissionSecondButton:
            return "Phone.Book.Search.Microphone.NoPermissionSecondButton"
        case .phoneBookSearchNoResults:
            return "Phone.Book.Search.NoResults"
        case .myDeviceHeaderInfo:
            return "MyDevice.HeaderInfo"
        case .myDeviceUser:
            return "MyDevice.User"
        case .myDevicePassword:
            return "MyDevice.Password"
        case .myDeviceExpireInfo:
            return "MyDevice.ExpireInfo"
        case .myDeviceCreateNewPass:
            return "MyDevice.CreateNewPass"
        case .myDeviceCopied:
            return "MyDevice.Copied"
        case .agendaText:
            return "Agenda.Text"
        case .agendaNewVisitOption:
            return "Agenda.NewVisitOption"
        case .agendaVisitListOption:
            return "Agenda.VisitListOption"
        case .agendaMenuHeader:
            return "Agenda.MenuHeader"
        case .agendaMenuText:
            return "Agenda.MenuText"
        case .agendaQuestionText:
            return "Agenda.QuestionText"
        case .agendaSearchWithCustomerNo:
            return "Agenda.SearchWithCustomerNo"
        case .agendaDetailedSearch:
            return "Agenda.DetailedSearch"
        case .agendaCustomerNo:
            return "Agenda.CustomerNo"
        case .agendaSearchButton:
            return "Agenda.SearchButton"
        case .agendaCustomerInformation:
            return "Agenda.CustomerInformation"
        case .agendaCustomerInformationSeeAll:
            return "Agenda.CustomerInformationSeeAll"
        case .agendaVisitRequest:
            return "Agenda.VisitRequest"
        case .agendaVisitReqSubmitPopup:
            return "Agenda.VisitReqSubmitPopup"
        case .agendaVisitListStartDate:
            return "Agenda.VisitListStartDate"
        case .agendaVisitListEndDate:
            return "Agenda.VisitListEndDate"
        case .agendaBranch:
            return "Agenda.Branch"
        case .agendaVisitList:
            return "Agenda.VisitList"
        case .agendaVisitListList:
            return "Agenda.VisitListList"
        case .agendaCustomerName:
            return "Agenda.CustomerName"
        case .agendaCustomerSecondName:
            return "Agenda.CustomerSecondName"
        case .agendaCustomerSurname:
            return "Agenda.CustomerSurname"
        case .agendaShortname:
            return "Agenda.Shortname"
        case .agendaCitizenshipNumber:
            return "Agenda.CitizenshipNumber"
        case .agendaTaxNo:
            return "Agenda.TaxNo"
        case .agendaMenuTextSubmit:
            return "Agenda.MenuTextSubmit"
        case .agendaVisitDate:
            return "Agenda.VisitDate"
        case .agendaPersonelVisit:
            return "Agenda.PersonelVisit"
        case .agendaPortfoyCode:
            return "Agenda.PortfoyCode"
        case .agendaPYVisit:
            return "Agenda.PYVisit"
        case .agendaVisitReason:
            return "Agenda.VisitReason"
        case .agendaVisitResult:
            return "Agenda.VisitResult"
        case .agendaVisitNote:
            return "Agenda.VisitNote"
        case .agendaVisitSubmit:
            return "Agenda.VisitSubmit"
        case .agendaResourceResult:
            return "Agenda.ResourceResult"
        case .agendaResourceResultCusNo:
            return "Agenda.ResourceResultCusNo"
        case .agendaResourceResultTCKN:
            return "Agenda.ResourceResultTCKN"
        case .agendaResourceResultVKN:
            return "Agenda.ResourceResultVKN"
        case .agendaResourceResultStatus:
            return "Agenda.ResourceResultStatus"
        case .agendaCreateContact:
            return "Agenda.CreateContact"
        case .agendaCreateContactInfo:
            return "Agenda.CreateContactInfo"
        case .agendaCreateContactTCKN:
            return "Agenda.CreateContactTCKN"
        case .agendaCreateContactPhoneNumber:
            return "Agenda.CreateContactPhoneNumber"
        case .agendaCreateContactBirthDate:
            return "Agenda.CreateContactBirthDate"
        case .agendaCreateContactCreate:
            return "Agenda.CreateContactCreate"
        case .agendaCreateContactResultInfo:
            return "Agenda.CreateContactResultInfo"
        case .agendaVisitListOptionDateMsg:
            return "Agenda.VisitListOptionDateMsg"
        case .agendaVisitListOptionDateMsg1:
            return "Agenda.VisitListOptionDateMsg1"
        case .agendaVisitDetail:
            return "Agenda.VisitDetail"
        case .agendaIsRevisitCustomer:
            return "Agenda.IsRevisitCustomer"
        case .agendaRevisitCustomerDate:
            return "Agenda.RevisitCustomerDate"
        case .agendaIsSoldSomethingToCustomer:
            return "Agenda.IsSoldSomethingToCustomer"
        case .agendaCreateCorporateInfo:
            return "Agenda.CreateCorporateInfo"
        case .agendaCreateCorporateVisitPer:
            return "Agenda.CreateCorporateVisitPer"
        case .agendaCreateCorporateFirmAuth:
            return "Agenda.CreateCorporateFirmAuth"
        case .agendaCreateCorporateFirmAuthTitle:
            return "Agenda.CreateCorporateFirmAuthTitle"
        case .agendaCreateCorporateFirmSummaryActivity:
            return "Agenda.CreateCorporateFirmSummaryActivity"
        case .agendaCreateCorporateFirmAction:
            return "Agenda.CreateCorporateFirmAction"
        case .agendaCreateCorporateGoods:
            return "Agenda.CreateCorporateGoods"
        case .agendaCreateCorporateBManagerComment:
            return "Agenda.CreateCorporateBManagerComment"
        case .agendaCreateCorporateAggrecultureAddress:
            return "Agenda.CreateCorporateAggrecultureAddress"
        case .agendaCreateCorporateEmployeeCount:
            return "Agenda.CreateCorporateEmployeeCount"
        case .agendaCreateCorporateMountlySallary:
            return "Agenda.CreateCorporateMountlySallary"
        case .agendaCreateCorporateSallaryBank:
            return "Agenda.CreateCorporateSallaryBank"
        case .agendaCreateCorporateSallaryBankAggrement:
            return "Agenda.CreateCorporateSallaryBankAggrement"
        case .agendaCreateCorporateAggrementEndDate:
            return "Agenda.CreateCorporateAggrementEndDate"
        case .agendaCreateCorporateFirmSector:
            return "Agenda.CreateCorporateFirmSector"
        case .agendaCreateCorporateConsolideBankRisk:
            return "Agenda.CreateCorporateConsolideBankRisk"
        case .agendaCreateCorporateConsolideEndorsment:
            return "Agenda.CreateCorporateConsolideEndorsment"
        case .agendaCreateCorporateContinue:
            return "Agenda.CreateCorporateContinue"
        case .agendaVisitSubject:
            return "Agenda.VisitSubject"
        case .softOtpCreatePinHeader:
            return "SoftOtp.CreatePin.Header"
        case .softOtpCreatePinInfo:
            return "SoftOtp.CreatePin.Info"
        case .softOtpCreatePinWarning:
            return "SoftOtp.CreatePin.Warning"
        case .softOtpCreatePinButton:
            return "SoftOtp.CreatePin.Button"
        case .softOtpSMSInfo:
            return "SoftOtp.SMS.Info"
        case .softOtpSMSPlaceHolder:
            return "SoftOtp.SMS.PlaceHolder"
        case .softOtpSMSButton:
            return "SoftOtp.SMS.Button"
        case .softOtpHeader:
            return "SoftOtp.Header"
        case .softOtpChangeInfo:
            return "SoftOtp.ChangeInfo"
        case .softOtpChangeButton:
            return "SoftOtp.ChangeButton"
        case .softOtpPinInfo:
            return "SoftOtp.Pin.Info"
        case .softOtpPinButton:
            return "SoftOtp.Pin.Button"
        case .softOtpChangePinHeader:
            return "SoftOtp.ChangePin.Header"
        case .softOtpChangePinInfo:
            return "SoftOtp.ChangePin.Info"
        case .softOtpChangePinWarning:
            return "SoftOtp.ChangePin.Warning"
        case .softOtpChangePinButton:
            return "SoftOtpChangePinButton"
        case .softOtpCompleteInfo:
            return "SoftOtp.CompleteInfo"
        case .softOtpSmsConfirmation:
            return "SoftOtp.SmsVerification.Header"
        case .softOtpSmsVerificationInfo:
            return "SoftOtp.SmsVerification.Info"
        case .softOtpPinPlaceHolder:
            return "SoftOtp.Pin.PlaceHolder"
        case .softOtpPinPlaceHolderAgain:
            return "SoftOtp.Pin.PlaceHolderAgain"
        case .softOtpCreatePinUserName:
            return "SoftOtp.CreatePin.UserName"
        case .softOtpPinCopied:
            return "SoftOtp.PinCopied"
        case .softOtpDifferentPin:
            return "SoftOtp.DifferentPin"
        case .softOtpWrongPin:
            return "SoftOtp.WrongPin"
        case .softOtpChangeCompleteInfo:
            return "SoftOtp.ChangeCompleteInfo"
        case .softOtpWarningPinCount:
            return "SoftOtp.WarningPinCount"
        case .softOtpWarningPinCountText:
            return "SoftOtp.WarningPinCountText"
        case .softOtpWarningPinEmpty:
            return "SoftOtp.WarningPinEmpty"
        case .softOtpWarningSMSOTP:
            return "SoftOtp.WarningSMSOTP"
        case .softOtpWarningWrongPin:
            return "SoftOtp.WarningWrongPin"
        case .softOtpCreatePinWarningAgainEmpty:
            return "SoftOtp.CreatePin.WarningAgainEmpty"
        case .biometricActivationTitle:
            return "BiometricActivation.Title"
        case .biometricLoginExp:
            return "BiometricLogin.Exp"
        case .biometricLoginActivationMessage:
            return "BiometricLogin.Exp"
        case .biometricLoginActivateButton:
            return "BiometricLogin.ActivateButton"
        case .biometricLoginPopUpMessage:
            return "BiometricLogin.PopUpMessage"
        case .biometricLoginPopUpCancel:
            return "BiometricLogin.PopUpCancel"
        case .biometricLoginContinue:
            return "BiometricLogin.Continue"
        case .biometricLoginCancelButton:
            return "BiometricLogin.CancelButton"
        case .biometricLoginCancelMessage:
            return "BiometricLogin.CancelMessage"
        case .biometricLoginNotEnrolled:
            return "BiometricLogin.NotEnrolled"
        case .biometricLoginPermission:
            return "BiometricLogin.Permission"
        case .biometricLoginSettingsButton:
            return "BiometricLogin.SettingsButton"
        case .biometricLoginErrorMessage:
            return "BiometricLogin.ErrorMessage"
        case .biometricLoginID:
            return "BiometricLogin.ID"
        case .biometricLoginCancelInfo:
            return "BiometricLogin.CancelInfo"
        case .biometricLoginPopUpLogin:
            return "BiometricLogin.PopUpLogin"
        case .rotaRota:
            return "Rota.Rota"
        case .rotaProcessNo:
            return "Rota.ProcessNo"
        case .rotaProcessTask:
            return "Rota.ProcessTask"
        case .rotaProcessApprove:
            return "Rota.ProcessApprove"
        case .rotaEmptyFlow:
            return "Rota.EmptyFlow"
        case .remoteWorkHeader:
            return "RemoteWork.Header"
        case .remoteWorkRemoteStartDate:
            return "RemoteWork.RemootStartDate"
        case .remoteWorkRemoteFinishDate:
            return "RemoteWork.RemootFinishDate"
        case .remoteWorkTotalDayCount:
            return "RemoteWork.TotalDayCount"
        case .remoteWorkTotalHoliday:
            return "RemoteWork.TotalHoliday"
        case .remoteWorkNetDayCount:
            return "RemoteWork.NetDayCount"
        case .remoteWorkExplanation:
            return "RemoteWork.Explanation"
        case .remoteWorkButton:
            return "RemoteWork.Button"
        case .remoteWorkWarningAllText:
            return "RemoteWork.WarningAllText"
        case .remoteWorkInfoText:
            return "RemoteWork.InfoText"
        case .remoteWorkWarningDateStart:
            return "RemoteWork.WarningDateStart"
        case .remoteWorkWarningDateEnd:
            return "RemoteWork.WarningDateEnd"
        case .beamerPackageNo:
            return "Beamer.PackageNo"
        case .beamerUser:
            return "Beamer.User"
        case .beamerPlanDate:
            return "Beamer.PlanDate"
        case .beamercriteria:
            return "Beamer.criteria"
        case .beamerplannedPublishDate:
            return "Beamer.plannedPublishDate"
        case .beamerrecordDate:
            return "Beamer.recordDate"
        case .beamerapplicationName:
            return "Beamer.applicationName"
        case .beamerenvRelationName:
            return "Beamer.envRelationName"
        case .beamerpublishType:
            return "Beamer.publishType"
        case .beameruserName:
            return "Beamer.userName"
        case .beamerunvalued:
            return "Beamer.unvalued"
        case .beameraccepted:
            return "Beamer.accepted"
        case .beamerrejected:
            return "Beamer.rejected"
        case .beamerpublishText:
            return "Beamer.publishText"
        case .beamerdmlText:
            return "Beamer.dmlText"
        case .beamerdescription:
            return "Beamer.description"
        case .beamerDetailHeader:
            return "Beamer.DetailHeader"
        case .beamerDetailRejectedButton:
            return "Beamer.DetailRejectedButton"
        case .beamerDetailAcceptedButton:
            return "Beamer.DetailAcceptedButton"
        case .beamerFilterClearButton:
            return "Beamer.FilterClearButton"
        case .beamerFilterSearchButton:
            return "Beamer.FilterSearchButton"
        case .beamerFilterHeader:
            return "Beamer.FilterHeader"
        case .beamerFilterPackageNo:
            return "Beamer.FilterPackageNo"
        case .beamerFilterPlanedDate:
            return "Beamer.FilterPlanedDate"
        case .beamerFilterApp:
            return "Beamer.FilterApp"
        case .beamerFilterUser:
            return "Beamer.FilterUser"
        case .beamerFilterEnvRelationName:
            return "Beamer.FilterEnvRelationName"
        case .beamerFilterUnvalued:
            return "Beamer.FilterUnvalued"
        case .delegationHeader:
            return "Delegation.Header"
        case .delegationExplanationText:
            return "Delegation.ExplanationText"
        case .delegationNewDelegation:
            return "Delegation.NewDelegation"
        case .delegationFollowUpCancel:
            return "Delegation.FollowUpCancel"
        case .delegationSearchUser:
            return "Delegation.SearchUser"
        case .delegationFlow:
            return "Delegation.Flow"
        case .delegationStatus:
            return "Delegation.Status"
        case .delegationDelegate:
            return "Delegation.Delegate"
        case .delegationDelegateText:
            return "Delegation.DelegateText"
        case .delegationUser:
            return "Delegation.User"
        case .delegationStartDate:
            return "Delegation.StartDate"
        case .delegationStartTime:
            return "Delegation.StartTime"
        case .delegationEndDate:
            return "Delegation.EndDate"
        case .delegationEndTime:
            return "Delegation.EndTime"
        case .delegationCompleted:
            return "Delegation.Completed"
        case .delegationCompletedText:
            return "Delegation.CompletedText"
        case .delegationFlowRole:
            return "Delegation.FlowRole"
        case .delegationWarning:
            return "Delegation.Warning"
        case .delegationWarningText:
            return "Delegation.WarningText"
        case .delegationUserNotFound:
            return "Delegation.UserNotFound"
        case .delegationContinue:
            return "Delegation.Continue"
        case .transportationDate:
            return "Transportation.Date"
        case .transportationRoute:
            return "Transportation.Route"
        case .transportationSelectRoute:
            return "Transportation.SelectRoute"
        case .transportationSearchRoute:
            return "Transportation.SearchRoute"
        case .transportationText:
            return "Transportation.Text"
        case .transportationMorning:
            return "Transportation.Morning"
        case .transportationEvening:
            return "Transportation.Evening"
        case .transportationBoth:
            return "Transportation.Both"
        case .transportationSave:
            return "Transportation.Save"
        case .leaveMenuAnnualLeave:
            return "Leave.MenuAnnualLeave"
        case .leaveHeaderTitle:
            return "Leave.HeaderTitle"
        case .leaveHeaderInfo:
            return "Leave.HeaderInfo"
        case .leaveExcuseLeave:
            return "Leave.ExcuseLeave"
        case .leaveHealthReport:
            return "Leave.HealthReport"
        case .leaveMaternityLeave:
            return "Leave.MaternityLeave"
        case .leaveBreastFeeding:
            return "Leave.BreastFeeding"
        case .leaveFreeLeaving:
            return "Leave.FreeLeaving"
        case .leaveExcuseLeaveInfo:
            return "Leave.ExcuseLeave.Info"
        case .leaveExcuseLeaveAdministrativeLeave:
            return "Leave.ExcuseLeave.AdministrativeLeave"
        case .leaveExcuseLeaveMarriedLeave:
            return "Leave.ExcuseLeave.MarriedLeave"
        case .leaveExcuseLeavePaternityLeave:
            return "Leave.ExcuseLeave.PaternityLeave"
        case .leaveExcuseLeaveMedicalDisaster:
            return "Leave.ExcuseLeave.MedicalDisaster"
        case .leaveExcuseLeaveRelocationLeave:
            return "Leave.ExcuseLeave.RelocationLeave"
        case .leaveExcuseLeaveChildMarried:
            return "Leave.ExcuseLeave.ChildMarried"
        case .leaveExcuseLeaveDeathOfFirstDegreeRelative:
            return "Leave.ExcuseLeave.DeathOfFirstDegreeRelative"
        case .leaveExcuseLeaveIlnessOfFirstDegreeRelative:
            return "Leave.ExcuseLeave.IlnessOfFirstDegreeRelative"
        case .leaveExcuseLeavePublicHoliday:
            return "Leave.ExcuseLeave.PublicHoliday"
        case .leaveExcuseLeavePageTitle:
            return "Leave.ExcuseLeave.PageTitle"
        case .leaveExcuseLeavePagePageInfo:
            return "Leave.ExcuseLeave.PagePageInfo"
        case .leaveExcuseLeaveStartDate:
            return "Leave.ExcuseLeave.StartDate"
        case .leaveExcuseLeaveEndDate:
            return "Leave.ExcuseLeave.EndDate"
        case .leaveExcuseLeaveTotalDay:
            return "Leave.ExcuseLeave.TotalDay"
        case .leaveExcuseLeaveUsageLeavingDay:
            return "Leave.ExcuseLeave.UsageLeavingDay"
        case .leaveExcuseLeaveContactNumberInHoliday:
            return "Leave.ExcuseLeave.ContactNumberInHoliday"
        case .leaveExcuseLeaveLastStepInfo:
            return "Leave.ExcuseLeave.LastStepInfo"
        case .leaveExcuseLeaveConfirmationButtonInfo:
            return "Leave.ExcuseLeave.ConfirmationButtonInfo"
        case .leaveAnnualLeavePageTitle:
            return "Leave.AnnualLeave.PageTitle"
        case .leaveAnnualLeaveHeaderInfo:
            return "Leave.AnnualLeave.HeaderInfo"
        case .leaveGeneralOtherContactNumberInHoliday:
            return "Leave.General.OtherContactNumberInHoliday"
        case .leaveHealthReportHeader:
            return "Leave.HealthReport.Header"
        case .leaveHealthReportDocumentInfoText:
            return "Leave.HealthReport.DocumentInfoText"
        case .leaveGeneralExplanation:
            return "Leave.General.Explanation"
        case .leaveFreeLeavingPageHeader:
            return "Leave.FreeLeaving.PageHeader"
        case .leaveFreeLeavingFreePostpartumLeave:
            return "Leave.FreeLeaving.FreePostpartumLeave"
        case .leaveFreeLeavingOtherFreeLeave:
            return "Leave.FreeLeaving.OtherFreeLeave"
        case .leaveFreeLeavingPageInfoText:
            return "Leave.FreeLeaving.PageInfoText"
        case .leaveFreeLeavingSecondPageText:
            return "Leave.FreeLeaving.SecondPageText"
        case .leaveMaternityLeaveSinglePregnancy:
            return "Leave.MaternityLeave.SinglePregnancy"
        case .leaveMaternityLeaveTwinPregnancyAndOthers:
            return "Leave.MaternityLeave.TwinPregnancyAndOthers"
        case .leaveBreastFeedingOneDayInWeek:
            return "Leave.BreastFeeding.OneDayInWeek"
        case .leaveBreastFeedingOneAndHalfHoursInDay:
            return "Leave.BreastFeeding.OneAndHalfHoursInDay"
        case .leaveBreastFeedingPreferinInfoText:
            return "Leave.BreastFeeding.PreferinInfoText"
        case .leaveBreastFeedingMonday:
            return "Leave.BreastFeeding.Monday"
        case .leaveBreastFeedingTuesday:
            return "Leave.BreastFeeding.Tuesday"
        case .leaveBreastFeedingWednesday:
            return "Leave.BreastFeeding.Wednesday"
        case .leaveBreastFeedingThursday:
            return "Leave.BreastFeeding.Thursday"
        case .leaveBreastFeedingFriday:
            return "Leave.BreastFeeding.Friday"
        case .leaveBreastFeedingPreferingHoursText:
            return "Leave.BreastFeeding.PreferingHoursText"
        case .leaveBreastFeedingFirstPreferingHours:
            return "Leave.BreastFeeding.FirstPreferingHours"
        case .leaveBreastFeedingSecondPreferingHours:
            return "Leave.BreastFeeding.SecondPreferingHours"
        case .leaveBreastFeedingThirdPreferingHours:
            return "Leave.BreastFeeding.ThirdPreferingHours"
        case .leaveBreastFeedingFourthPreferingHours:
            return "Leave.BreastFeeding.FourthPreferingHours"
        case .leaveBreastFeedingFifthPreferingHours:
            return "Leave.BreastFeeding.FifthPreferingHours"
        case .leaveBreastFeedingSixthPreferingHours:
            return "Leave.BreastFeeding.SixthPreferingHours"
        case .leaveGeneralContinueButton:
            return "Leave.General.ContinueButton"
        case .leaveGeneralCity:
            return "Leave.General.City"
        case .leaveGeneralTown:
            return "Leave.General.Town"
        case .leaveGeneralStreet:
            return "Leave.General.Street"
        case .leaveGeneralTelephoneNumber:
            return "Leave.General.TelephoneNumber"
        case .leaveGeneralAdressVallidityDate:
            return "Leave.General.AdressVallidityDate"
        case .leaveGeneralAdressVallidityApproval:
            return "Leave.General.AdressVallidityApproval"
        case .leaveGeneralSendButton:
            return "Leave.General.SendButton"
        }
    }

    var parameters: [String] {
        switch self {
        case let .softOtpCompleteInfo(userName):
            return [userName]
        case let .myDeviceExpireInfo(remainingDay):
            return [remainingDay]
        case let .beamerDetailHeader(packageNo):
            return [packageNo]
        case let .agendaResourceResultCusNo(customerNumber):
            return [customerNumber]
        case let .agendaResourceResultTCKN(citizenShipNumber):
            return [citizenShipNumber]
        case let .agendaResourceResultVKN(taxNumber):
            return [taxNumber]
        case let .agendaResourceResultStatus(status):
            return [status]
        default:
            return []
        }
    }

    var prefix: String {
        switch self {
        default:
            return ""
        }
    }

    var suffix: String {
        switch self {
        case let .biometricActivationTitle(biometricTypeId):
            return biometricTypeId
        case let .biometricLoginActivationMessage(biometricTypeId):
            return biometricTypeId
        case let .biometricLoginPopUpMessage(biometricTypeId):
            return biometricTypeId
        case let .biometricLoginPopUpCancel(biometricTypeId):
            return biometricTypeId
        case let .biometricLoginCancelMessage(biometricTypeId):
            return biometricTypeId
        case let .biometricLoginNotEnrolled(biometricTypeId):
            return biometricTypeId
        case let .biometricLoginPermission(biometricTypeId):
            return biometricTypeId
        case let .biometricLoginID(biometricTypeId):
            return biometricTypeId
        case let .biometricLoginCancelInfo(biometricTypeId):
            return biometricTypeId
        case let .biometricLoginPopUpLogin(biometricTypeId):
            return biometricTypeId
        default:
            return ""
        }
    }

    var value: String {
        return resource(for: key, prefix: prefix, suffix: suffix, params: parameters)
    }

    var languageDict: [String: String]? {
        if PersistentKeeper.shared.isAppRunningTest {
            return SessionKeeper.shared.languageDictForTest
        } else {
            return PersistentKeeper.shared.languageDict
        }
    }
}

extension ResourceKey {
    public func resource(for key: String, prefix: String = "", suffix: String = "") -> String {
        if let resource = languageDict?[prefix + key + suffix] {
            return resource.replacingOccurrences(of: "\\n", with: "\n")
        } else {
            return ""
        }
    }

    private func resource(for key: String, prefix: String = "", suffix: String = "", params: [String]) -> String {
        var resourceStr = resource(for: key, prefix: prefix, suffix: suffix)
        guard !resourceStr.isEmpty else { return "" }
        guard resourceStr.contains("{"), resourceStr.contains("}") else { return resourceStr }

        var paramIndex = 0
        for param in params {
            let searchParamPattern = "{\(paramIndex)}"
            paramIndex += 1
            guard resourceStr.contains(searchParamPattern) else { continue }
            resourceStr = resourceStr.replacingOccurrences(of: searchParamPattern, with: param)
        }
        return resourceStr
    }
}
